test_login_1.py             22 INFO     ========登录模块测试用例执行开始========【1】========
get_phone.py                29 INFO     【LE67A06290097275】设备连接正常
remote_connection.py       117 INFO     Could not connect to port 4723 on host 127.0.0.1
remote_connection.py       136 INFO     Could not get IP address for host: 127.0.0.1
remote_connection.py       388 DEBUG    POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{"platformName": "Android", "appium:platformVersion": 6.0, "appium:deviceName": "LE67A06290097275", "appium:appPackage": "com.cmic.college", "appium:udid": "LE67A06290097275", "appium:appActivity": "com.cmcc.cmrcs.android.ui.activities.WelcomeActivity", "appium:noReset": true, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}]}, "desiredCapabilities": {"platformName": "Android", "platformVersion": 6.0, "deviceName": "LE67A06290097275", "appPackage": "com.cmic.college", "udid": "LE67A06290097275", "appActivity": "com.cmcc.cmrcs.android.ui.activities.WelcomeActivity", "noReset": true, "unicodeKeyboard": true, "resetKeyboard": true, "automationName": "uiautomator2"}}
connectionpool.py          205 DEBUG    Starting new HTTP connection (1): 127.0.0.1:4723
retry.py                   400 DEBUG    Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
connectionpool.py          662 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028960D54278>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
connectionpool.py          205 DEBUG    Starting new HTTP connection (2): 127.0.0.1:4723
retry.py                   400 DEBUG    Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
connectionpool.py          662 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028960D54518>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
connectionpool.py          205 DEBUG    Starting new HTTP connection (3): 127.0.0.1:4723
retry.py                   400 DEBUG    Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
connectionpool.py          662 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028960D54710>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
connectionpool.py          205 DEBUG    Starting new HTTP connection (4): 127.0.0.1:4723
driver.py                   45 WARNING  【LE_X620】连接【com.cmic.college】异常，重启APPIUM服务再次连接
start_appium.py             29 INFO     port 4723不存在，可以使用 
start_appium.py             19 INFO     appium服务127.0.0.1，端口4723启动成功
remote_connection.py       117 INFO     Could not connect to port 4723 on host 127.0.0.1
remote_connection.py       136 INFO     Could not get IP address for host: 127.0.0.1
remote_connection.py       388 DEBUG    POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{"platformName": "Android", "appium:platformVersion": 6.0, "appium:deviceName": "LE67A06290097275", "appium:appPackage": "com.cmic.college", "appium:udid": "LE67A06290097275", "appium:appActivity": "com.cmcc.cmrcs.android.ui.activities.WelcomeActivity", "appium:noReset": true, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}]}, "desiredCapabilities": {"platformName": "Android", "platformVersion": 6.0, "deviceName": "LE67A06290097275", "appPackage": "com.cmic.college", "udid": "LE67A06290097275", "appActivity": "com.cmcc.cmrcs.android.ui.activities.WelcomeActivity", "noReset": true, "unicodeKeyboard": true, "resetKeyboard": true, "automationName": "uiautomator2"}}
connectionpool.py          205 DEBUG    Starting new HTTP connection (1): 127.0.0.1:4723
connectionpool.py          393 DEBUG    http://127.0.0.1:4723 "POST /wd/hub/session HTTP/1.1" 200 1144
remote_connection.py       440 DEBUG    Finished Request
remote_connection.py       388 DEBUG    POST http://127.0.0.1:4723/wd/hub/session/fc9b4fc8-708b-4b1c-9af6-0c7b57a47086/timeouts {"implicit": 20000, "sessionId": "fc9b4fc8-708b-4b1c-9af6-0c7b57a47086"}
connectionpool.py          205 DEBUG    Starting new HTTP connection (1): 127.0.0.1:4723
connectionpool.py          393 DEBUG    http://127.0.0.1:4723 "POST /wd/hub/session/fc9b4fc8-708b-4b1c-9af6-0c7b57a47086/timeouts HTTP/1.1" 200 14
remote_connection.py       440 DEBUG    Finished Request
remote_connection.py       388 DEBUG    POST http://127.0.0.1:4723/wd/hub/session/fc9b4fc8-708b-4b1c-9af6-0c7b57a47086/network_connection {"parameters": {"type": 4}, "sessionId": "fc9b4fc8-708b-4b1c-9af6-0c7b57a47086"}
connectionpool.py          205 DEBUG    Starting new HTTP connection (1): 127.0.0.1:4723
connectionpool.py          393 DEBUG    http://127.0.0.1:4723 "POST /wd/hub/session/fc9b4fc8-708b-4b1c-9af6-0c7b57a47086/network_connection HTTP/1.1" 200 11
remote_connection.py       440 DEBUG    Finished Request
mobile_operating.py         29 INFO     网络数据模式开启成功